# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total hours'),
        ),
    ]
