# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'verbose_name': 'Completed hour', 'verbose_name_plural': 'Completed hours'},
        ),
        migrations.AddField(
            model_name='hours',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
