# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170708_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
