# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20170708_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='project',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
