# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20170708_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dead_date',
        ),
        migrations.AddField(
            model_name='project',
            name='velocity',
            field=models.IntegerField(default=1),
        ),
    ]
