# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170709_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Closed day')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='closed_days',
            field=models.ManyToManyField(to='project.ClosedDays'),
        ),
    ]
