# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170709_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closeddays',
            options={'verbose_name': 'Closed day', 'verbose_name_plural': 'Closed days'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='closed_days',
        ),
        migrations.AddField(
            model_name='closeddays',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
