# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20170709_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeddays',
            name='day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Closed day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hours',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
